
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnalysisExportViewsService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class AnalysisExportViewsService
    extends Service
{

    private final static URL ANALYSISEXPORTVIEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANALYSISEXPORTVIEWSSERVICE_EXCEPTION;
    private final static QName ANALYSISEXPORTVIEWSSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "AnalysisExportViewsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANALYSISEXPORTVIEWSSERVICE_WSDL_LOCATION = url;
        ANALYSISEXPORTVIEWSSERVICE_EXCEPTION = e;
    }

    public AnalysisExportViewsService() {
        super(__getWsdlLocation(), ANALYSISEXPORTVIEWSSERVICE_QNAME);
    }

    public AnalysisExportViewsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANALYSISEXPORTVIEWSSERVICE_QNAME, features);
    }

    public AnalysisExportViewsService(URL wsdlLocation) {
        super(wsdlLocation, ANALYSISEXPORTVIEWSSERVICE_QNAME);
    }

    public AnalysisExportViewsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANALYSISEXPORTVIEWSSERVICE_QNAME, features);
    }

    public AnalysisExportViewsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnalysisExportViewsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnalysisExportViewsServiceSoap
     */
    @WebEndpoint(name = "AnalysisExportViewsServiceSoap")
    public AnalysisExportViewsServiceSoap getAnalysisExportViewsServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "AnalysisExportViewsServiceSoap"), AnalysisExportViewsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnalysisExportViewsServiceSoap
     */
    @WebEndpoint(name = "AnalysisExportViewsServiceSoap")
    public AnalysisExportViewsServiceSoap getAnalysisExportViewsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "AnalysisExportViewsServiceSoap"), AnalysisExportViewsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANALYSISEXPORTVIEWSSERVICE_EXCEPTION!= null) {
            throw ANALYSISEXPORTVIEWSSERVICE_EXCEPTION;
        }
        return ANALYSISEXPORTVIEWSSERVICE_WSDL_LOCATION;
    }

}
