
package oracle.bi.web.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AnalysisExportViewsServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnalysisExportViewsServiceSoap {


    /**
     * 
     * @param reportParams
     * @param report
     * @param reportViewName
     * @param executionOptions
     * @param sessionID
     * @param outputFormat
     * @return
     *     returns oracle.bi.web.soap.AnalysisExportResult
     */
    @WebMethod(action = "#initiateAnalysisExport")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "initiateAnalysisExport", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.InitiateAnalysisExport")
    @ResponseWrapper(localName = "initiateAnalysisExportResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.InitiateAnalysisExportResult")
    public AnalysisExportResult initiateAnalysisExport(
        @WebParam(name = "report", targetNamespace = "urn://oracle.bi.webservices/v12")
        ReportRef report,
        @WebParam(name = "outputFormat", targetNamespace = "urn://oracle.bi.webservices/v12")
        AnalysisExportOutputFormat outputFormat,
        @WebParam(name = "executionOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        AnalysisExportExecutionOptions executionOptions,
        @WebParam(name = "reportParams", targetNamespace = "urn://oracle.bi.webservices/v12")
        ReportParams reportParams,
        @WebParam(name = "reportViewName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String reportViewName,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param queryID
     * @return
     *     returns oracle.bi.web.soap.AnalysisExportResult
     */
    @WebMethod(action = "#completeAnalysisExport")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "completeAnalysisExport", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CompleteAnalysisExport")
    @ResponseWrapper(localName = "completeAnalysisExportResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CompleteAnalysisExportResult")
    public AnalysisExportResult completeAnalysisExport(
        @WebParam(name = "queryID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String queryID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
