
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConditionService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class ConditionService
    extends Service
{

    private final static URL CONDITIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONDITIONSERVICE_EXCEPTION;
    private final static QName CONDITIONSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "ConditionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONDITIONSERVICE_WSDL_LOCATION = url;
        CONDITIONSERVICE_EXCEPTION = e;
    }

    public ConditionService() {
        super(__getWsdlLocation(), CONDITIONSERVICE_QNAME);
    }

    public ConditionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONDITIONSERVICE_QNAME, features);
    }

    public ConditionService(URL wsdlLocation) {
        super(wsdlLocation, CONDITIONSERVICE_QNAME);
    }

    public ConditionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONDITIONSERVICE_QNAME, features);
    }

    public ConditionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConditionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConditionServiceSoap
     */
    @WebEndpoint(name = "ConditionServiceSoap")
    public ConditionServiceSoap getConditionServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ConditionServiceSoap"), ConditionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConditionServiceSoap
     */
    @WebEndpoint(name = "ConditionServiceSoap")
    public ConditionServiceSoap getConditionServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ConditionServiceSoap"), ConditionServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONDITIONSERVICE_EXCEPTION!= null) {
            throw CONDITIONSERVICE_EXCEPTION;
        }
        return CONDITIONSERVICE_WSDL_LOCATION;
    }

}
