
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IBotService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class IBotService
    extends Service
{

    private final static URL IBOTSERVICE_WSDL_LOCATION;
    private final static WebServiceException IBOTSERVICE_EXCEPTION;
    private final static QName IBOTSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "IBotService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IBOTSERVICE_WSDL_LOCATION = url;
        IBOTSERVICE_EXCEPTION = e;
    }

    public IBotService() {
        super(__getWsdlLocation(), IBOTSERVICE_QNAME);
    }

    public IBotService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IBOTSERVICE_QNAME, features);
    }

    public IBotService(URL wsdlLocation) {
        super(wsdlLocation, IBOTSERVICE_QNAME);
    }

    public IBotService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IBOTSERVICE_QNAME, features);
    }

    public IBotService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBotService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBotServiceSoap
     */
    @WebEndpoint(name = "IBotServiceSoap")
    public IBotServiceSoap getIBotServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "IBotServiceSoap"), IBotServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBotServiceSoap
     */
    @WebEndpoint(name = "IBotServiceSoap")
    public IBotServiceSoap getIBotServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "IBotServiceSoap"), IBotServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IBOTSERVICE_EXCEPTION!= null) {
            throw IBOTSERVICE_EXCEPTION;
        }
        return IBOTSERVICE_WSDL_LOCATION;
    }

}
