
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JobManagementService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class JobManagementService
    extends Service
{

    private final static URL JOBMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOBMANAGEMENTSERVICE_EXCEPTION;
    private final static QName JOBMANAGEMENTSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "JobManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOBMANAGEMENTSERVICE_WSDL_LOCATION = url;
        JOBMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public JobManagementService() {
        super(__getWsdlLocation(), JOBMANAGEMENTSERVICE_QNAME);
    }

    public JobManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOBMANAGEMENTSERVICE_QNAME, features);
    }

    public JobManagementService(URL wsdlLocation) {
        super(wsdlLocation, JOBMANAGEMENTSERVICE_QNAME);
    }

    public JobManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOBMANAGEMENTSERVICE_QNAME, features);
    }

    public JobManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JobManagementServiceSoap
     */
    @WebEndpoint(name = "JobManagementServiceSoap")
    public JobManagementServiceSoap getJobManagementServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "JobManagementServiceSoap"), JobManagementServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobManagementServiceSoap
     */
    @WebEndpoint(name = "JobManagementServiceSoap")
    public JobManagementServiceSoap getJobManagementServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "JobManagementServiceSoap"), JobManagementServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOBMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw JOBMANAGEMENTSERVICE_EXCEPTION;
        }
        return JOBMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
