
package oracle.bi.web.soap;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JobManagementServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JobManagementServiceSoap {


    /**
     * 
     * @param reportParams
     * @param report
     * @param segmentPath
     * @param segmentationOptions
     * @param sessionID
     * @param treeNodePath
     * @param filesystem
     * @param timeout
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#writeListFiles")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "writeListFiles", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.WriteListFiles")
    @ResponseWrapper(localName = "writeListFilesResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.WriteListFilesResult")
    public JobInfo writeListFiles(
        @WebParam(name = "report", targetNamespace = "urn://oracle.bi.webservices/v12")
        ReportRef report,
        @WebParam(name = "reportParams", targetNamespace = "urn://oracle.bi.webservices/v12")
        ReportParams reportParams,
        @WebParam(name = "segmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String segmentPath,
        @WebParam(name = "treeNodePath", targetNamespace = "urn://oracle.bi.webservices/v12")
        TreeNodePath treeNodePath,
        @WebParam(name = "segmentationOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        SegmentationOptions segmentationOptions,
        @WebParam(name = "filesystem", targetNamespace = "urn://oracle.bi.webservices/v12")
        String filesystem,
        @WebParam(name = "timeout", targetNamespace = "urn://oracle.bi.webservices/v12")
        BigInteger timeout,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param jobID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#getJobInfo")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getJobInfo", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobInfo")
    @ResponseWrapper(localName = "getJobInfoResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobInfoResult")
    public JobInfo getJobInfo(
        @WebParam(name = "jobID", targetNamespace = "urn://oracle.bi.webservices/v12")
        BigInteger jobID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param jobID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#cancelJob")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "cancelJob", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelJob")
    @ResponseWrapper(localName = "cancelJobResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelJobResult")
    public JobInfo cancelJob(
        @WebParam(name = "jobID", targetNamespace = "urn://oracle.bi.webservices/v12")
        BigInteger jobID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param segmentPath
     * @param segmentationOptions
     * @param sessionID
     * @param treePath
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#getCounts")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getCounts", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetCounts")
    @ResponseWrapper(localName = "getCountsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetCountsResult")
    public JobInfo getCounts(
        @WebParam(name = "segmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String segmentPath,
        @WebParam(name = "treePath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String treePath,
        @WebParam(name = "segmentationOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        SegmentationOptions segmentationOptions,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param segmentPath
     * @param sessionID
     * @param treePath
     * @return
     *     returns oracle.bi.web.soap.PromptedColumnInfo
     */
    @WebMethod(action = "#getPromptedColumns")
    @WebResult(name = "ColumnInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getPromptedColumns", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetPromptedColumns")
    @ResponseWrapper(localName = "getPromptedColumnsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetPromptedColumnsResult")
    public PromptedColumnInfo getPromptedColumns(
        @WebParam(name = "segmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String segmentPath,
        @WebParam(name = "treePath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String treePath,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param ignoreCacheRef
     * @param segmentPath
     * @param sessionID
     * @param treePath
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#purgeCache")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "purgeCache", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.PurgeCache")
    @ResponseWrapper(localName = "purgeCacheResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.PurgeCacheResult")
    public JobInfo purgeCache(
        @WebParam(name = "segmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String segmentPath,
        @WebParam(name = "treePath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String treePath,
        @WebParam(name = "ignoreCacheRef", targetNamespace = "urn://oracle.bi.webservices/v12")
        Boolean ignoreCacheRef,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param segmentPath
     * @param refresh
     * @param sessionID
     * @param treePath
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#prepareCache")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "prepareCache", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.PrepareCache")
    @ResponseWrapper(localName = "prepareCacheResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.PrepareCacheResult")
    public JobInfo prepareCache(
        @WebParam(name = "segmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String segmentPath,
        @WebParam(name = "treePath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String treePath,
        @WebParam(name = "refresh", targetNamespace = "urn://oracle.bi.webservices/v12")
        Boolean refresh,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param savedSegmentPath
     * @param segmentPath
     * @param segmentationOptions
     * @param sessionID
     * @param treeNodePath
     * @param srCustomLabel
     * @param appendStaticSegment
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#saveResultSet")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "saveResultSet", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.SaveResultSet")
    @ResponseWrapper(localName = "saveResultSetResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.SaveResultSetResult")
    public JobInfo saveResultSet(
        @WebParam(name = "segmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String segmentPath,
        @WebParam(name = "treeNodePath", targetNamespace = "urn://oracle.bi.webservices/v12")
        TreeNodePath treeNodePath,
        @WebParam(name = "savedSegmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String savedSegmentPath,
        @WebParam(name = "segmentationOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        SegmentationOptions segmentationOptions,
        @WebParam(name = "SRCustomLabel", targetNamespace = "urn://oracle.bi.webservices/v12")
        String srCustomLabel,
        @WebParam(name = "appendStaticSegment", targetNamespace = "urn://oracle.bi.webservices/v12")
        Boolean appendStaticSegment,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param guiDs
     * @param segmentPath
     * @param sessionID
     * @param targetLevel
     * @return
     *     returns oracle.bi.web.soap.JobInfo
     */
    @WebMethod(action = "#deleteResultSet")
    @WebResult(name = "jobInfo", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "deleteResultSet", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteResultSet")
    @ResponseWrapper(localName = "deleteResultSetResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteResultSetResult")
    public JobInfo deleteResultSet(
        @WebParam(name = "targetLevel", targetNamespace = "urn://oracle.bi.webservices/v12")
        String targetLevel,
        @WebParam(name = "GUIDs", targetNamespace = "urn://oracle.bi.webservices/v12")
        ArrayOfGUIDs guiDs,
        @WebParam(name = "segmentPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String segmentPath,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
