
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KPIAssessmentService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class KPIAssessmentService
    extends Service
{

    private final static URL KPIASSESSMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException KPIASSESSMENTSERVICE_EXCEPTION;
    private final static QName KPIASSESSMENTSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "KPIAssessmentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KPIASSESSMENTSERVICE_WSDL_LOCATION = url;
        KPIASSESSMENTSERVICE_EXCEPTION = e;
    }

    public KPIAssessmentService() {
        super(__getWsdlLocation(), KPIASSESSMENTSERVICE_QNAME);
    }

    public KPIAssessmentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KPIASSESSMENTSERVICE_QNAME, features);
    }

    public KPIAssessmentService(URL wsdlLocation) {
        super(wsdlLocation, KPIASSESSMENTSERVICE_QNAME);
    }

    public KPIAssessmentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KPIASSESSMENTSERVICE_QNAME, features);
    }

    public KPIAssessmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KPIAssessmentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KPIAssessmentServiceSoap
     */
    @WebEndpoint(name = "KPIAssessmentServiceSoap")
    public KPIAssessmentServiceSoap getKPIAssessmentServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "KPIAssessmentServiceSoap"), KPIAssessmentServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KPIAssessmentServiceSoap
     */
    @WebEndpoint(name = "KPIAssessmentServiceSoap")
    public KPIAssessmentServiceSoap getKPIAssessmentServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "KPIAssessmentServiceSoap"), KPIAssessmentServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KPIASSESSMENTSERVICE_EXCEPTION!= null) {
            throw KPIASSESSMENTSERVICE_EXCEPTION;
        }
        return KPIASSESSMENTSERVICE_WSDL_LOCATION;
    }

}
