
package oracle.bi.web.soap;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KPIAssessmentServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KPIAssessmentServiceSoap {


    /**
     * 
     * @param kpiColumnList
     * @param kpiVariableList
     * @param executionOptions
     * @param sessionID
     * @param kpiRequestList
     * @return
     *     returns oracle.bi.web.soap.KPIExecutionStatus
     */
    @WebMethod(action = "#executeKPI")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "executeKPI", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExecuteKPI")
    @ResponseWrapper(localName = "executeKPIResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExecuteKPIResult")
    public KPIExecutionStatus executeKPI(
        @WebParam(name = "executionOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIExecutionOptions executionOptions,
        @WebParam(name = "kpiRequestList", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIRequestList kpiRequestList,
        @WebParam(name = "kpiColumnList", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIColumnList kpiColumnList,
        @WebParam(name = "kpiVariableList", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIVariableList kpiVariableList,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param kpiColumnList
     * @param reportPath
     * @param kpiVariableList
     * @param sessionID
     * @param kpiRequest
     * @return
     *     returns oracle.bi.web.soap.KPIGenerateDrillToStatus
     */
    @WebMethod(action = "#generateDrillTo")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "generateDrillTo", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GenerateDrillTo")
    @ResponseWrapper(localName = "generateDrillToResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GenerateDrillToResult")
    public KPIGenerateDrillToStatus generateDrillTo(
        @WebParam(name = "kpiRequest", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIRequest kpiRequest,
        @WebParam(name = "kpiColumnList", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIColumnList kpiColumnList,
        @WebParam(name = "kpiVariableList", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIVariableList kpiVariableList,
        @WebParam(name = "reportPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String reportPath,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param kpiExecutionID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.KPIExecutionStatus
     */
    @WebMethod(action = "#fetchKPIAssessment")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "fetchKPIAssessment", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.FetchKPIAssessment")
    @ResponseWrapper(localName = "fetchKPIAssessmentResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.FetchKPIAssessmentResult")
    public KPIExecutionStatus fetchKPIAssessment(
        @WebParam(name = "kpiExecutionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiExecutionID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param kpiExecutionID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.KPICancelationStatus
     */
    @WebMethod(action = "#cancelKPIExecution")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "cancelKPIExecution", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelKPIExecution")
    @ResponseWrapper(localName = "cancelKPIExecutionResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelKPIExecutionResult")
    public KPICancelationStatus cancelKPIExecution(
        @WebParam(name = "kpiExecutionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiExecutionID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param dimensionID
     * @param rowsPerFetch
     * @param sessionID
     * @param kpiPath
     * @return
     *     returns oracle.bi.web.soap.KPIDimensionLOVExecutionStatus
     */
    @WebMethod(action = "#executeKPIDimensionLOVQuery")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "executeKPIDimensionLOVQuery", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExecuteKPIDimensionLOVQuery")
    @ResponseWrapper(localName = "executeKPIDimensionLOVQueryResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExecuteKPIDimensionLOVQueryResult")
    public KPIDimensionLOVExecutionStatus executeKPIDimensionLOVQuery(
        @WebParam(name = "rowsPerFetch", targetNamespace = "urn://oracle.bi.webservices/v12")
        BigInteger rowsPerFetch,
        @WebParam(name = "kpiPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiPath,
        @WebParam(name = "dimensionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String dimensionID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param kpiLOVExecutionID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.KPIDimensionLOVExecutionStatus
     */
    @WebMethod(action = "#fetchNextKPIDimensionLOV")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "fetchNextKPIDimensionLOV", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.FetchNextKPIDimensionLOV")
    @ResponseWrapper(localName = "fetchNextKPIDimensionLOVResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.FetchNextKPIDimensionLOVResult")
    public KPIDimensionLOVExecutionStatus fetchNextKPIDimensionLOV(
        @WebParam(name = "kpiLOVExecutionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiLOVExecutionID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param kpiWatchlistPath
     * @param sessionID
     * @param kpiWatchlistXML
     * @return
     *     returns oracle.bi.web.soap.KPIDimensionReferences
     */
    @WebMethod(action = "#getKPIWatchlistDimensions")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getKPIWatchlistDimensions", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetKPIWatchlistDimensions")
    @ResponseWrapper(localName = "getKPIWatchlistDimensionsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetKPIWatchlistDimensionsResult")
    public KPIDimensionReferences getKPIWatchlistDimensions(
        @WebParam(name = "kpiWatchlistPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiWatchlistPath,
        @WebParam(name = "kpiWatchlistXML", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiWatchlistXML,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param kpiContributionWheelXML
     * @param kpiContributionWheelPath
     * @return
     *     returns oracle.bi.web.soap.KPIDimensionReferences
     */
    @WebMethod(action = "#getKPIContributionWheelDimensions")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getKPIContributionWheelDimensions", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetKPIContributionWheelDimensions")
    @ResponseWrapper(localName = "getKPIContributionWheelDimensionsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetKPIContributionWheelDimensionsResult")
    public KPIDimensionReferences getKPIContributionWheelDimensions(
        @WebParam(name = "kpiContributionWheelPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiContributionWheelPath,
        @WebParam(name = "kpiContributionWheelXML", targetNamespace = "urn://oracle.bi.webservices/v12")
        String kpiContributionWheelXML,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
