
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MetadataService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class MetadataService
    extends Service
{

    private final static URL METADATASERVICE_WSDL_LOCATION;
    private final static WebServiceException METADATASERVICE_EXCEPTION;
    private final static QName METADATASERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "MetadataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METADATASERVICE_WSDL_LOCATION = url;
        METADATASERVICE_EXCEPTION = e;
    }

    public MetadataService() {
        super(__getWsdlLocation(), METADATASERVICE_QNAME);
    }

    public MetadataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), METADATASERVICE_QNAME, features);
    }

    public MetadataService(URL wsdlLocation) {
        super(wsdlLocation, METADATASERVICE_QNAME);
    }

    public MetadataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METADATASERVICE_QNAME, features);
    }

    public MetadataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetadataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MetadataServiceSoap
     */
    @WebEndpoint(name = "MetadataServiceSoap")
    public MetadataServiceSoap getMetadataServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "MetadataServiceSoap"), MetadataServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetadataServiceSoap
     */
    @WebEndpoint(name = "MetadataServiceSoap")
    public MetadataServiceSoap getMetadataServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "MetadataServiceSoap"), MetadataServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METADATASERVICE_EXCEPTION!= null) {
            throw METADATASERVICE_EXCEPTION;
        }
        return METADATASERVICE_WSDL_LOCATION;
    }

}
