
package oracle.bi.web.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MetadataServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetadataServiceSoap {


    /**
     * 
     * @param sessionID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "#clearQueryCache")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "clearQueryCache", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ClearQueryCache")
    @ResponseWrapper(localName = "clearQueryCacheResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ClearQueryCacheResult")
    public Boolean clearQueryCache(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns java.util.List<oracle.bi.web.soap.SASubjectArea>
     */
    @WebMethod(action = "#getSubjectAreas")
    @WebResult(name = "subjectArea", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getSubjectAreas", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetSubjectAreas")
    @ResponseWrapper(localName = "getSubjectAreasResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetSubjectAreasResult")
    public List<SASubjectArea> getSubjectAreas(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param subjectAreaName
     * @param sessionID
     * @param includeXSAs
     * @return
     *     returns java.util.List<oracle.bi.web.soap.SASubjectArea>
     */
    @WebMethod(action = "#getRelatedSubjectAreas")
    @WebResult(name = "subjectArea", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getRelatedSubjectAreas", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetRelatedSubjectAreas")
    @ResponseWrapper(localName = "getRelatedSubjectAreasResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetRelatedSubjectAreasResult")
    public List<SASubjectArea> getRelatedSubjectAreas(
        @WebParam(name = "subjectAreaName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String subjectAreaName,
        @WebParam(name = "includeXSAs", targetNamespace = "urn://oracle.bi.webservices/v12")
        boolean includeXSAs,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param subjectAreaName
     * @param sessionID
     * @param detailsLevel
     * @return
     *     returns oracle.bi.web.soap.SASubjectArea
     */
    @WebMethod(action = "#describeSubjectArea")
    @WebResult(name = "subjectArea", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "describeSubjectArea", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DescribeSubjectArea")
    @ResponseWrapper(localName = "describeSubjectAreaResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DescribeSubjectAreaResult")
    public SASubjectArea describeSubjectArea(
        @WebParam(name = "subjectAreaName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String subjectAreaName,
        @WebParam(name = "detailsLevel", targetNamespace = "urn://oracle.bi.webservices/v12")
        SASubjectAreaDetails detailsLevel,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param subjectAreaName
     * @param sessionID
     * @param detailsLevel
     * @param tableName
     * @return
     *     returns oracle.bi.web.soap.SATable
     */
    @WebMethod(action = "#describeTable")
    @WebResult(name = "table", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "describeTable", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DescribeTable")
    @ResponseWrapper(localName = "describeTableResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DescribeTableResult")
    public SATable describeTable(
        @WebParam(name = "subjectAreaName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String subjectAreaName,
        @WebParam(name = "tableName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String tableName,
        @WebParam(name = "detailsLevel", targetNamespace = "urn://oracle.bi.webservices/v12")
        SATableDetails detailsLevel,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param subjectAreaName
     * @param sessionID
     * @param tableName
     * @param columnName
     * @return
     *     returns oracle.bi.web.soap.SAColumn
     */
    @WebMethod(action = "#describeColumn")
    @WebResult(name = "column", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "describeColumn", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DescribeColumn")
    @ResponseWrapper(localName = "describeColumnResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DescribeColumnResult")
    public SAColumn describeColumn(
        @WebParam(name = "subjectAreaName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String subjectAreaName,
        @WebParam(name = "tableName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String tableName,
        @WebParam(name = "columnName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String columnName,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param logLevel
     * @param domain
     * @param id
     * @param sessionID
     */
    @WebMethod(action = "#reloadLogConfiguration")
    @RequestWrapper(localName = "reloadLogConfiguration", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ReloadLogConfiguration")
    @ResponseWrapper(localName = "reloadLogConfigurationResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ReloadLogConfigurationResult")
    public void reloadLogConfiguration(
        @WebParam(name = "logLevel", targetNamespace = "urn://oracle.bi.webservices/v12")
        LogReloadLevel logLevel,
        @WebParam(name = "domain", targetNamespace = "urn://oracle.bi.webservices/v12")
        LogReloadDomain domain,
        @WebParam(name = "id", targetNamespace = "urn://oracle.bi.webservices/v12")
        String id,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "#reloadMetadata")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "reloadMetadata", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ReloadMetadata")
    @ResponseWrapper(localName = "reloadMetadataResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ReloadMetadataResult")
    public Boolean reloadMetadata(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
