
package oracle.bi.web.soap;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MultiTenancyManagementServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MultiTenancyManagementServiceSoap {


    /**
     * 
     * @param tenantID
     * @param sessionID
     */
    @WebMethod(action = "#provisionTenant")
    @RequestWrapper(localName = "provisionTenant", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ProvisionTenant")
    @ResponseWrapper(localName = "provisionTenantResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ProvisionTenantResult")
    public void provisionTenant(
        @WebParam(name = "tenantID", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<String> tenantID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param serviceInstanceConfigParams
     * @param sessionID
     */
    @WebMethod(action = "#provisionServiceInstance")
    @RequestWrapper(localName = "provisionServiceInstance", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ProvisionServiceInstance")
    @ResponseWrapper(localName = "provisionServiceInstanceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ProvisionServiceInstanceResult")
    public void provisionServiceInstance(
        @WebParam(name = "serviceInstanceConfigParams", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<ServiceInstanceConfigParams> serviceInstanceConfigParams,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param serviceInstanceConfigParams
     * @param sessionID
     */
    @WebMethod(action = "#updateServiceInstance")
    @RequestWrapper(localName = "updateServiceInstance", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateServiceInstance")
    @ResponseWrapper(localName = "updateServiceInstanceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateServiceInstanceResult")
    public void updateServiceInstance(
        @WebParam(name = "serviceInstanceConfigParams", targetNamespace = "urn://oracle.bi.webservices/v12")
        ServiceInstanceConfigParams serviceInstanceConfigParams,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param tenantID
     * @param sessionID
     */
    @WebMethod(action = "#unprovisionTenant")
    @RequestWrapper(localName = "unprovisionTenant", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UnprovisionTenant")
    @ResponseWrapper(localName = "unprovisionTenantResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UnprovisionTenantResult")
    public void unprovisionTenant(
        @WebParam(name = "tenantID", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<String> tenantID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param serviceInstanceID
     * @param sessionID
     */
    @WebMethod(action = "#unprovisionServiceInstance")
    @RequestWrapper(localName = "unprovisionServiceInstance", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UnprovisionServiceInstance")
    @ResponseWrapper(localName = "unprovisionServiceInstanceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UnprovisionServiceInstanceResult")
    public void unprovisionServiceInstance(
        @WebParam(name = "serviceInstanceID", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<String> serviceInstanceID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param useMtom
     * @param tenantID
     * @param sessionID
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod(action = "#archiveTenant")
    @WebResult(name = "archive", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "archiveTenant", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ArchiveTenant")
    @ResponseWrapper(localName = "archiveTenantResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ArchiveTenantResult")
    public DataHandler archiveTenant(
        @WebParam(name = "tenantID", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<String> tenantID,
        @WebParam(name = "useMtom", targetNamespace = "urn://oracle.bi.webservices/v12")
        boolean useMtom,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param archiveOptions
     * @param useMtom
     * @param sessionID
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod(action = "#archiveTenantEx")
    @WebResult(name = "archive", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "archiveTenantEx", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ArchiveTenantEx")
    @ResponseWrapper(localName = "archiveTenantExResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ArchiveTenantExResult")
    public DataHandler archiveTenantEx(
        @WebParam(name = "archiveOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        ArchiveOptions archiveOptions,
        @WebParam(name = "useMtom", targetNamespace = "urn://oracle.bi.webservices/v12")
        boolean useMtom,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param tenantID
     * @param archive
     * @param sessionID
     */
    @WebMethod(action = "#unarchiveTenant")
    @RequestWrapper(localName = "unarchiveTenant", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UnarchiveTenant")
    @ResponseWrapper(localName = "unarchiveTenantResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UnarchiveTenantResult")
    public void unarchiveTenant(
        @WebParam(name = "archive", targetNamespace = "urn://oracle.bi.webservices/v12")
        DataHandler archive,
        @WebParam(name = "tenantID", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<String> tenantID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param tenantID
     * @param archive
     * @param sessionID
     */
    @WebMethod(action = "#restoreTenant")
    @RequestWrapper(localName = "restoreTenant", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.RestoreTenant")
    @ResponseWrapper(localName = "restoreTenantResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.RestoreTenantResult")
    public void restoreTenant(
        @WebParam(name = "archive", targetNamespace = "urn://oracle.bi.webservices/v12")
        DataHandler archive,
        @WebParam(name = "tenantID", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<String> tenantID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param archive
     * @param restoreOptions
     * @param sessionID
     */
    @WebMethod(action = "#restoreTenantEx")
    @RequestWrapper(localName = "restoreTenantEx", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.RestoreTenantEx")
    @ResponseWrapper(localName = "restoreTenantExResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.RestoreTenantExResult")
    public void restoreTenantEx(
        @WebParam(name = "archive", targetNamespace = "urn://oracle.bi.webservices/v12")
        DataHandler archive,
        @WebParam(name = "restoreOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        RestoreOptions restoreOptions,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     */
    @WebMethod(action = "#clearRoleHierarchyCache")
    @RequestWrapper(localName = "clearRoleHierarchyCache", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ClearRoleHierarchyCache")
    @ResponseWrapper(localName = "clearRoleHierarchyCacheResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ClearRoleHierarchyCacheResult")
    public void clearRoleHierarchyCache(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
