
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReplicationService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class ReplicationService
    extends Service
{

    private final static URL REPLICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPLICATIONSERVICE_EXCEPTION;
    private final static QName REPLICATIONSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "ReplicationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPLICATIONSERVICE_WSDL_LOCATION = url;
        REPLICATIONSERVICE_EXCEPTION = e;
    }

    public ReplicationService() {
        super(__getWsdlLocation(), REPLICATIONSERVICE_QNAME);
    }

    public ReplicationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPLICATIONSERVICE_QNAME, features);
    }

    public ReplicationService(URL wsdlLocation) {
        super(wsdlLocation, REPLICATIONSERVICE_QNAME);
    }

    public ReplicationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPLICATIONSERVICE_QNAME, features);
    }

    public ReplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReplicationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReplicationServiceSoap
     */
    @WebEndpoint(name = "ReplicationServiceSoap")
    public ReplicationServiceSoap getReplicationServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ReplicationServiceSoap"), ReplicationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReplicationServiceSoap
     */
    @WebEndpoint(name = "ReplicationServiceSoap")
    public ReplicationServiceSoap getReplicationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ReplicationServiceSoap"), ReplicationServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPLICATIONSERVICE_EXCEPTION!= null) {
            throw REPLICATIONSERVICE_EXCEPTION;
        }
        return REPLICATIONSERVICE_WSDL_LOCATION;
    }

}
