
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReportEditingService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class ReportEditingService
    extends Service
{

    private final static URL REPORTEDITINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPORTEDITINGSERVICE_EXCEPTION;
    private final static QName REPORTEDITINGSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "ReportEditingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTEDITINGSERVICE_WSDL_LOCATION = url;
        REPORTEDITINGSERVICE_EXCEPTION = e;
    }

    public ReportEditingService() {
        super(__getWsdlLocation(), REPORTEDITINGSERVICE_QNAME);
    }

    public ReportEditingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPORTEDITINGSERVICE_QNAME, features);
    }

    public ReportEditingService(URL wsdlLocation) {
        super(wsdlLocation, REPORTEDITINGSERVICE_QNAME);
    }

    public ReportEditingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPORTEDITINGSERVICE_QNAME, features);
    }

    public ReportEditingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportEditingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReportEditingServiceSoap
     */
    @WebEndpoint(name = "ReportEditingServiceSoap")
    public ReportEditingServiceSoap getReportEditingServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ReportEditingServiceSoap"), ReportEditingServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportEditingServiceSoap
     */
    @WebEndpoint(name = "ReportEditingServiceSoap")
    public ReportEditingServiceSoap getReportEditingServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ReportEditingServiceSoap"), ReportEditingServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORTEDITINGSERVICE_EXCEPTION!= null) {
            throw REPORTEDITINGSERVICE_EXCEPTION;
        }
        return REPORTEDITINGSERVICE_WSDL_LOCATION;
    }

}
