
package oracle.bi.web.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SAWAdministrationServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SAWAdministrationServiceSoap {


    /**
     * 
     * @param logLevel
     * @param domain
     * @param id
     * @param sessionID
     */
    @WebMethod(action = "#reloadLogConfiguration")
    @RequestWrapper(localName = "reloadLogConfiguration", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ReloadLogConfiguration")
    @ResponseWrapper(localName = "reloadLogConfigurationResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ReloadLogConfigurationResult")
    public void reloadLogConfiguration(
        @WebParam(name = "logLevel", targetNamespace = "urn://oracle.bi.webservices/v12")
        LogReloadLevel logLevel,
        @WebParam(name = "domain", targetNamespace = "urn://oracle.bi.webservices/v12")
        LogReloadDomain domain,
        @WebParam(name = "id", targetNamespace = "urn://oracle.bi.webservices/v12")
        String id,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param cspWhitelistXml
     * @param sessionID
     */
    @WebMethod(action = "#updateCSPWhitelist")
    @RequestWrapper(localName = "updateCSPWhitelist", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateCSPWhitelist")
    @ResponseWrapper(localName = "updateCSPWhitelistResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateCSPWhitelistResult")
    public void updateCSPWhitelist(
        @WebParam(name = "cspWhitelistXml", targetNamespace = "urn://oracle.bi.webservices/v12")
        String cspWhitelistXml,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "#getCSPWhitelist")
    @WebResult(name = "resultXml", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getCSPWhitelist", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetCSPWhitelist")
    @ResponseWrapper(localName = "getCSPWhitelistResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetCSPWhitelistResult")
    public String getCSPWhitelist(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     */
    @WebMethod(action = "#deleteCSPWhitelist")
    @RequestWrapper(localName = "deleteCSPWhitelist", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteCSPWhitelist")
    @ResponseWrapper(localName = "deleteCSPWhitelistResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteCSPWhitelistResult")
    public void deleteCSPWhitelist(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
