
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SAWSessionService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class SAWSessionService
    extends Service
{

    private final static URL SAWSESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAWSESSIONSERVICE_EXCEPTION;
    private final static QName SAWSESSIONSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "SAWSessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAWSESSIONSERVICE_WSDL_LOCATION = url;
        SAWSESSIONSERVICE_EXCEPTION = e;
    }

    public SAWSessionService() {
        super(__getWsdlLocation(), SAWSESSIONSERVICE_QNAME);
    }

    public SAWSessionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAWSESSIONSERVICE_QNAME, features);
    }

    public SAWSessionService(URL wsdlLocation) {
        super(wsdlLocation, SAWSESSIONSERVICE_QNAME);
    }

    public SAWSessionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAWSESSIONSERVICE_QNAME, features);
    }

    public SAWSessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAWSessionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SAWSessionServiceSoap
     */
    @WebEndpoint(name = "SAWSessionServiceSoap")
    public SAWSessionServiceSoap getSAWSessionServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "SAWSessionServiceSoap"), SAWSessionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAWSessionServiceSoap
     */
    @WebEndpoint(name = "SAWSessionServiceSoap")
    public SAWSessionServiceSoap getSAWSessionServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "SAWSessionServiceSoap"), SAWSessionServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAWSESSIONSERVICE_EXCEPTION!= null) {
            throw SAWSESSIONSERVICE_EXCEPTION;
        }
        return SAWSESSIONSERVICE_WSDL_LOCATION;
    }

}
