
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SchedulerService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class SchedulerService
    extends Service
{

    private final static URL SCHEDULERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCHEDULERSERVICE_EXCEPTION;
    private final static QName SCHEDULERSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "SchedulerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCHEDULERSERVICE_WSDL_LOCATION = url;
        SCHEDULERSERVICE_EXCEPTION = e;
    }

    public SchedulerService() {
        super(__getWsdlLocation(), SCHEDULERSERVICE_QNAME);
    }

    public SchedulerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCHEDULERSERVICE_QNAME, features);
    }

    public SchedulerService(URL wsdlLocation) {
        super(wsdlLocation, SCHEDULERSERVICE_QNAME);
    }

    public SchedulerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCHEDULERSERVICE_QNAME, features);
    }

    public SchedulerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchedulerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SchedulerServiceSoap
     */
    @WebEndpoint(name = "SchedulerServiceSoap")
    public SchedulerServiceSoap getSchedulerServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "SchedulerServiceSoap"), SchedulerServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SchedulerServiceSoap
     */
    @WebEndpoint(name = "SchedulerServiceSoap")
    public SchedulerServiceSoap getSchedulerServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "SchedulerServiceSoap"), SchedulerServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCHEDULERSERVICE_EXCEPTION!= null) {
            throw SCHEDULERSERVICE_EXCEPTION;
        }
        return SCHEDULERSERVICE_WSDL_LOCATION;
    }

}
