
package oracle.bi.web.soap;

import java.math.BigInteger;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SchedulerServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SchedulerServiceSoap {


    /**
     * 
     * @param sessionID
     * @param jobFilter
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod(action = "#getJobReferences")
    @WebResult(name = "jobReference", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getJobReferences", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobReferences")
    @ResponseWrapper(localName = "getJobReferencesResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobReferencesResult")
    public List<Long> getJobReferences(
        @WebParam(name = "jobFilter", targetNamespace = "urn://oracle.bi.webservices/v12")
        JobFilter jobFilter,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param jobReference
     * @return
     *     returns oracle.bi.web.soap.Job
     */
    @WebMethod(action = "#getJob")
    @WebResult(name = "job", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getJob", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJob")
    @ResponseWrapper(localName = "getJobResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobResult")
    public Job getJob(
        @WebParam(name = "jobReference", targetNamespace = "urn://oracle.bi.webservices/v12")
        long jobReference,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param jobInstanceFilter
     * @param sessionID
     * @return
     *     returns java.util.List<oracle.bi.web.soap.JobReferenceAndInstanceReferences>
     */
    @WebMethod(action = "#getJobInstanceReferences")
    @WebResult(name = "jobReferenceAndInstanceReferences", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getJobInstanceReferences", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobInstanceReferences")
    @ResponseWrapper(localName = "getJobInstanceReferencesResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobInstanceReferencesResult")
    public List<JobReferenceAndInstanceReferences> getJobInstanceReferences(
        @WebParam(name = "jobInstanceFilter", targetNamespace = "urn://oracle.bi.webservices/v12")
        JobInstanceFilter jobInstanceFilter,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param jobInstanceReference
     * @param sessionID
     * @param jobReference
     * @return
     *     returns oracle.bi.web.soap.JobInstance
     */
    @WebMethod(action = "#getJobInstance")
    @WebResult(name = "jobInstance", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getJobInstance", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobInstance")
    @ResponseWrapper(localName = "getJobInstanceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetJobInstanceResult")
    public JobInstance getJobInstance(
        @WebParam(name = "jobReference", targetNamespace = "urn://oracle.bi.webservices/v12")
        long jobReference,
        @WebParam(name = "jobInstanceReference", targetNamespace = "urn://oracle.bi.webservices/v12")
        BigInteger jobInstanceReference,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param jobInstanceReference
     * @param sessionID
     * @param jobReference
     * @return
     *     returns boolean
     */
    @WebMethod(action = "#cancelJobInstance")
    @WebResult(name = "cancelJobInstanceResponse", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "cancelJobInstance", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelJobInstance")
    @ResponseWrapper(localName = "cancelJobInstanceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelJobInstanceResult")
    public boolean cancelJobInstance(
        @WebParam(name = "jobReference", targetNamespace = "urn://oracle.bi.webservices/v12")
        long jobReference,
        @WebParam(name = "jobInstanceReference", targetNamespace = "urn://oracle.bi.webservices/v12")
        BigInteger jobInstanceReference,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param timeoutSecs
     */
    @WebMethod(action = "#suspendService")
    @RequestWrapper(localName = "suspendService", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.SuspendService")
    @ResponseWrapper(localName = "suspendServiceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.SuspendServiceResult")
    public void suspendService(
        @WebParam(name = "timeoutSecs", targetNamespace = "urn://oracle.bi.webservices/v12")
        long timeoutSecs,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param exportFile
     * @param sessionID
     * @return
     *     returns long
     */
    @WebMethod(action = "#exportService")
    @WebResult(name = "agentsExported", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "exportService", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExportService")
    @ResponseWrapper(localName = "exportServiceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExportServiceResult")
    public long exportService(
        @WebParam(name = "exportFile", targetNamespace = "urn://oracle.bi.webservices/v12")
        String exportFile,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns long
     */
    @WebMethod(action = "#deleteService")
    @WebResult(name = "agentsDeleted", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "deleteService", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteService")
    @ResponseWrapper(localName = "deleteServiceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteServiceResult")
    public long deleteService(
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param importFile
     * @param sessionID
     * @param agentsImported
     * @param agentsDeleted
     */
    @WebMethod(action = "#importService")
    @RequestWrapper(localName = "importService", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ImportService")
    @ResponseWrapper(localName = "importServiceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ImportServiceResult")
    public void importService(
        @WebParam(name = "importFile", targetNamespace = "urn://oracle.bi.webservices/v12")
        String importFile,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID,
        @WebParam(name = "agentsImported", targetNamespace = "urn://oracle.bi.webservices/v12", mode = WebParam.Mode.OUT)
        Holder<Long> agentsImported,
        @WebParam(name = "agentsDeleted", targetNamespace = "urn://oracle.bi.webservices/v12", mode = WebParam.Mode.OUT)
        Holder<Long> agentsDeleted);

    /**
     * 
     * @param catchUp
     * @param sessionID
     */
    @WebMethod(action = "#resumeService")
    @RequestWrapper(localName = "resumeService", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ResumeService")
    @ResponseWrapper(localName = "resumeServiceResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ResumeServiceResult")
    public void resumeService(
        @WebParam(name = "catchUp", targetNamespace = "urn://oracle.bi.webservices/v12")
        Boolean catchUp,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param jobReference
     * @return
     *     returns long
     */
    @WebMethod(action = "#removeJobs")
    @WebResult(name = "numberJobsRemoved", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "removeJobs", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.RemoveJobs")
    @ResponseWrapper(localName = "removeJobsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.RemoveJobsResult")
    public long removeJobs(
        @WebParam(name = "jobReference", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<Long> jobReference,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param purgeJobInstancesFilter
     * @param sessionID
     */
    @WebMethod(action = "#purgeJobInstances")
    @RequestWrapper(localName = "purgeJobInstances", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.PurgeJobInstances")
    @ResponseWrapper(localName = "purgeJobInstancesResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.PurgeJobInstancesResult")
    public void purgeJobInstances(
        @WebParam(name = "purgeJobInstancesFilter", targetNamespace = "urn://oracle.bi.webservices/v12")
        PurgeJobInstancesFilter purgeJobInstancesFilter,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
