
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScorecardAssessmentService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class ScorecardAssessmentService
    extends Service
{

    private final static URL SCORECARDASSESSMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORECARDASSESSMENTSERVICE_EXCEPTION;
    private final static QName SCORECARDASSESSMENTSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "ScorecardAssessmentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCORECARDASSESSMENTSERVICE_WSDL_LOCATION = url;
        SCORECARDASSESSMENTSERVICE_EXCEPTION = e;
    }

    public ScorecardAssessmentService() {
        super(__getWsdlLocation(), SCORECARDASSESSMENTSERVICE_QNAME);
    }

    public ScorecardAssessmentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORECARDASSESSMENTSERVICE_QNAME, features);
    }

    public ScorecardAssessmentService(URL wsdlLocation) {
        super(wsdlLocation, SCORECARDASSESSMENTSERVICE_QNAME);
    }

    public ScorecardAssessmentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORECARDASSESSMENTSERVICE_QNAME, features);
    }

    public ScorecardAssessmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScorecardAssessmentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScorecardAssessmentServiceSoap
     */
    @WebEndpoint(name = "ScorecardAssessmentServiceSoap")
    public ScorecardAssessmentServiceSoap getScorecardAssessmentServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ScorecardAssessmentServiceSoap"), ScorecardAssessmentServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScorecardAssessmentServiceSoap
     */
    @WebEndpoint(name = "ScorecardAssessmentServiceSoap")
    public ScorecardAssessmentServiceSoap getScorecardAssessmentServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "ScorecardAssessmentServiceSoap"), ScorecardAssessmentServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORECARDASSESSMENTSERVICE_EXCEPTION!= null) {
            throw SCORECARDASSESSMENTSERVICE_EXCEPTION;
        }
        return SCORECARDASSESSMENTSERVICE_WSDL_LOCATION;
    }

}
