
package oracle.bi.web.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScorecardAssessmentServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScorecardAssessmentServiceSoap {


    /**
     * 
     * @param kpiColumnList
     * @param executionOptions
     * @param variableList
     * @param scorecardPath
     * @param sessionID
     * @param nodeList
     * @return
     *     returns oracle.bi.web.soap.ScorecardExecutionStatus
     */
    @WebMethod(action = "#executeScorecard")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "executeScorecard", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExecuteScorecard")
    @ResponseWrapper(localName = "executeScorecardResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.ExecuteScorecardResult")
    public ScorecardExecutionStatus executeScorecard(
        @WebParam(name = "executionOptions", targetNamespace = "urn://oracle.bi.webservices/v12")
        ScorecardExecutionOptions executionOptions,
        @WebParam(name = "scorecardPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardPath,
        @WebParam(name = "nodeList", targetNamespace = "urn://oracle.bi.webservices/v12")
        ScorecardNodeList nodeList,
        @WebParam(name = "variableList", targetNamespace = "urn://oracle.bi.webservices/v12")
        ScorecardVariableList variableList,
        @WebParam(name = "kpiColumnList", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIColumnList kpiColumnList,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param scorecardExecutionID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.ScorecardExecutionStatus
     */
    @WebMethod(action = "#fetchScorecardAssessment")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "fetchScorecardAssessment", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.FetchScorecardAssessment")
    @ResponseWrapper(localName = "fetchScorecardAssessmentResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.FetchScorecardAssessmentResult")
    public ScorecardExecutionStatus fetchScorecardAssessment(
        @WebParam(name = "scorecardExecutionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardExecutionID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param kpiColumnList
     * @param reportPath
     * @param variableList
     * @param scorecardPath
     * @param sessionID
     * @param nodeType
     * @param nodeID
     * @param isDrillTo
     * @return
     *     returns oracle.bi.web.soap.ScorecardGenerateDrillToStatus
     */
    @WebMethod(action = "#generateKPIDrillTo")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "generateKPIDrillTo", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GenerateKPIDrillTo")
    @ResponseWrapper(localName = "generateKPIDrillToResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GenerateKPIDrillToResult")
    public ScorecardGenerateDrillToStatus generateKPIDrillTo(
        @WebParam(name = "scorecardPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardPath,
        @WebParam(name = "nodeID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String nodeID,
        @WebParam(name = "nodeType", targetNamespace = "urn://oracle.bi.webservices/v12")
        String nodeType,
        @WebParam(name = "reportPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String reportPath,
        @WebParam(name = "variableList", targetNamespace = "urn://oracle.bi.webservices/v12")
        ScorecardVariableList variableList,
        @WebParam(name = "kpiColumnList", targetNamespace = "urn://oracle.bi.webservices/v12")
        KPIColumnList kpiColumnList,
        @WebParam(name = "isDrillTo", targetNamespace = "urn://oracle.bi.webservices/v12")
        boolean isDrillTo,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param getFresh
     * @param scorecardPath
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.ScorecardDimensionReferences
     */
    @WebMethod(action = "#getScorecardKPIDimensions")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getScorecardKPIDimensions", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetScorecardKPIDimensions")
    @ResponseWrapper(localName = "getScorecardKPIDimensionsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetScorecardKPIDimensionsResult")
    public ScorecardDimensionReferences getScorecardKPIDimensions(
        @WebParam(name = "scorecardPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardPath,
        @WebParam(name = "getFresh", targetNamespace = "urn://oracle.bi.webservices/v12")
        Boolean getFresh,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param scorecardViewPath
     * @param scorecardViewXML
     * @param sessionID
     * @param type
     * @return
     *     returns oracle.bi.web.soap.ScorecardDimensionReferences
     */
    @WebMethod(action = "#getScorecardViewDimensions")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getScorecardViewDimensions", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetScorecardViewDimensions")
    @ResponseWrapper(localName = "getScorecardViewDimensionsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetScorecardViewDimensionsResult")
    public ScorecardDimensionReferences getScorecardViewDimensions(
        @WebParam(name = "type", targetNamespace = "urn://oracle.bi.webservices/v12")
        ScorecardViewType type,
        @WebParam(name = "scorecardViewPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardViewPath,
        @WebParam(name = "scorecardViewXML", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardViewXML,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param scorecardExecutionID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.ScorecardCancelationStatus
     */
    @WebMethod(action = "#cancelScorecardAssessment")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "cancelScorecardAssessment", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelScorecardAssessment")
    @ResponseWrapper(localName = "cancelScorecardAssessmentResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CancelScorecardAssessmentResult")
    public ScorecardCancelationStatus cancelScorecardAssessment(
        @WebParam(name = "scorecardExecutionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardExecutionID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param scorecardExecutionID
     * @param sessionID
     * @return
     *     returns oracle.bi.web.soap.ScorecardCloseStatus
     */
    @WebMethod(action = "#closeScorecardAssessment")
    @WebResult(targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "closeScorecardAssessment", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CloseScorecardAssessment")
    @ResponseWrapper(localName = "closeScorecardAssessmentResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.CloseScorecardAssessmentResult")
    public ScorecardCloseStatus closeScorecardAssessment(
        @WebParam(name = "scorecardExecutionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String scorecardExecutionID,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
