
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecurityService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class SecurityService
    extends Service
{

    private final static URL SECURITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECURITYSERVICE_EXCEPTION;
    private final static QName SECURITYSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "SecurityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECURITYSERVICE_WSDL_LOCATION = url;
        SECURITYSERVICE_EXCEPTION = e;
    }

    public SecurityService() {
        super(__getWsdlLocation(), SECURITYSERVICE_QNAME);
    }

    public SecurityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURITYSERVICE_QNAME, features);
    }

    public SecurityService(URL wsdlLocation) {
        super(wsdlLocation, SECURITYSERVICE_QNAME);
    }

    public SecurityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURITYSERVICE_QNAME, features);
    }

    public SecurityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecurityServiceSoap
     */
    @WebEndpoint(name = "SecurityServiceSoap")
    public SecurityServiceSoap getSecurityServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "SecurityServiceSoap"), SecurityServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityServiceSoap
     */
    @WebEndpoint(name = "SecurityServiceSoap")
    public SecurityServiceSoap getSecurityServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "SecurityServiceSoap"), SecurityServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURITYSERVICE_EXCEPTION!= null) {
            throw SECURITYSERVICE_EXCEPTION;
        }
        return SECURITYSERVICE_WSDL_LOCATION;
    }

}
