
package oracle.bi.web.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserPersonalizationServiceSoap", targetNamespace = "urn://oracle.bi.webservices/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserPersonalizationServiceSoap {


    /**
     * 
     * @param categoryPath
     * @param sessionID
     * @param catalogObjectPath
     */
    @WebMethod(action = "#addFavorite")
    @RequestWrapper(localName = "addFavorite", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.AddFavorite")
    @ResponseWrapper(localName = "addFavoriteResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.AddFavoriteResult")
    public void addFavorite(
        @WebParam(name = "catalogObjectPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String catalogObjectPath,
        @WebParam(name = "categoryPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String categoryPath,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param categoryPath
     * @param sessionID
     * @param categoryName
     */
    @WebMethod(action = "#addFavoriteCategory")
    @RequestWrapper(localName = "addFavoriteCategory", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.AddFavoriteCategory")
    @ResponseWrapper(localName = "addFavoriteCategoryResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.AddFavoriteCategoryResult")
    public void addFavoriteCategory(
        @WebParam(name = "categoryName", targetNamespace = "urn://oracle.bi.webservices/v12")
        String categoryName,
        @WebParam(name = "categoryPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String categoryPath,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param categoryPath
     * @param sessionID
     * @param catalogObjectPath
     */
    @WebMethod(action = "#deleteFavorite")
    @RequestWrapper(localName = "deleteFavorite", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteFavorite")
    @ResponseWrapper(localName = "deleteFavoriteResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteFavoriteResult")
    public void deleteFavorite(
        @WebParam(name = "catalogObjectPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String catalogObjectPath,
        @WebParam(name = "categoryPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String categoryPath,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param categoryPath
     * @param sessionID
     */
    @WebMethod(action = "#deleteFavoriteCategory")
    @RequestWrapper(localName = "deleteFavoriteCategory", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteFavoriteCategory")
    @ResponseWrapper(localName = "deleteFavoriteCategoryResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.DeleteFavoriteCategoryResult")
    public void deleteFavoriteCategory(
        @WebParam(name = "categoryPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String categoryPath,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param categoryPath
     * @param sessionID
     * @param categoriesOnly
     * @param recursive
     * @return
     *     returns java.util.List<oracle.bi.web.soap.FavoriteItem>
     */
    @WebMethod(action = "#getFavorites")
    @WebResult(name = "favoriteItem", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getFavorites", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetFavorites")
    @ResponseWrapper(localName = "getFavoritesResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetFavoritesResult")
    public List<FavoriteItem> getFavorites(
        @WebParam(name = "categoryPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String categoryPath,
        @WebParam(name = "recursive", targetNamespace = "urn://oracle.bi.webservices/v12")
        boolean recursive,
        @WebParam(name = "categoriesOnly", targetNamespace = "urn://oracle.bi.webservices/v12")
        boolean categoriesOnly,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param favoriteItem
     * @param sessionID
     */
    @WebMethod(action = "#updateFavorites")
    @RequestWrapper(localName = "updateFavorites", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateFavorites")
    @ResponseWrapper(localName = "updateFavoritesResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateFavoritesResult")
    public void updateFavorites(
        @WebParam(name = "favoriteItem", targetNamespace = "urn://oracle.bi.webservices/v12")
        List<FavoriteItem> favoriteItem,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param actionType
     * @param sessionID
     * @param catalogObjectPath
     */
    @WebMethod(action = "#updateMostRecents")
    @RequestWrapper(localName = "updateMostRecents", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateMostRecents")
    @ResponseWrapper(localName = "updateMostRecentsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.UpdateMostRecentsResult")
    public void updateMostRecents(
        @WebParam(name = "catalogObjectPath", targetNamespace = "urn://oracle.bi.webservices/v12")
        String catalogObjectPath,
        @WebParam(name = "actionType", targetNamespace = "urn://oracle.bi.webservices/v12")
        int actionType,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param listType
     * @return
     *     returns java.util.List<oracle.bi.web.soap.MRUItem>
     */
    @WebMethod(action = "#getMostRecents")
    @WebResult(name = "listItem", targetNamespace = "urn://oracle.bi.webservices/v12")
    @RequestWrapper(localName = "getMostRecents", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetMostRecents")
    @ResponseWrapper(localName = "getMostRecentsResult", targetNamespace = "urn://oracle.bi.webservices/v12", className = "oracle.bi.web.soap.GetMostRecentsResult")
    public List<MRUItem> getMostRecents(
        @WebParam(name = "listType", targetNamespace = "urn://oracle.bi.webservices/v12")
        int listType,
        @WebParam(name = "sessionID", targetNamespace = "urn://oracle.bi.webservices/v12")
        String sessionID);

}
