
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserPersonalizationService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class UserPersonalizationService
    extends Service
{

    private final static URL USERPERSONALIZATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERPERSONALIZATIONSERVICE_EXCEPTION;
    private final static QName USERPERSONALIZATIONSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "UserPersonalizationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERPERSONALIZATIONSERVICE_WSDL_LOCATION = url;
        USERPERSONALIZATIONSERVICE_EXCEPTION = e;
    }

    public UserPersonalizationService() {
        super(__getWsdlLocation(), USERPERSONALIZATIONSERVICE_QNAME);
    }

    public UserPersonalizationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERPERSONALIZATIONSERVICE_QNAME, features);
    }

    public UserPersonalizationService(URL wsdlLocation) {
        super(wsdlLocation, USERPERSONALIZATIONSERVICE_QNAME);
    }

    public UserPersonalizationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERPERSONALIZATIONSERVICE_QNAME, features);
    }

    public UserPersonalizationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserPersonalizationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserPersonalizationServiceSoap
     */
    @WebEndpoint(name = "UserPersonalizationServiceSoap")
    public UserPersonalizationServiceSoap getUserPersonalizationServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "UserPersonalizationServiceSoap"), UserPersonalizationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPersonalizationServiceSoap
     */
    @WebEndpoint(name = "UserPersonalizationServiceSoap")
    public UserPersonalizationServiceSoap getUserPersonalizationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "UserPersonalizationServiceSoap"), UserPersonalizationServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERPERSONALIZATIONSERVICE_EXCEPTION!= null) {
            throw USERPERSONALIZATIONSERVICE_EXCEPTION;
        }
        return USERPERSONALIZATIONSERVICE_WSDL_LOCATION;
    }

}
