
package oracle.bi.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XmlViewService", targetNamespace = "urn://oracle.bi.webservices/v12", wsdlLocation = "http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12")
public class XmlViewService
    extends Service
{

    private final static URL XMLVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException XMLVIEWSERVICE_EXCEPTION;
    private final static QName XMLVIEWSERVICE_QNAME = new QName("urn://oracle.bi.webservices/v12", "XmlViewService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7780/analytics/saw.dll/wsdl/v12");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XMLVIEWSERVICE_WSDL_LOCATION = url;
        XMLVIEWSERVICE_EXCEPTION = e;
    }

    public XmlViewService() {
        super(__getWsdlLocation(), XMLVIEWSERVICE_QNAME);
    }

    public XmlViewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XMLVIEWSERVICE_QNAME, features);
    }

    public XmlViewService(URL wsdlLocation) {
        super(wsdlLocation, XMLVIEWSERVICE_QNAME);
    }

    public XmlViewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XMLVIEWSERVICE_QNAME, features);
    }

    public XmlViewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XmlViewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XmlViewServiceSoap
     */
    @WebEndpoint(name = "XmlViewServiceSoap")
    public XmlViewServiceSoap getXmlViewServiceSoap() {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "XmlViewServiceSoap"), XmlViewServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XmlViewServiceSoap
     */
    @WebEndpoint(name = "XmlViewServiceSoap")
    public XmlViewServiceSoap getXmlViewServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn://oracle.bi.webservices/v12", "XmlViewServiceSoap"), XmlViewServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XMLVIEWSERVICE_EXCEPTION!= null) {
            throw XMLVIEWSERVICE_EXCEPTION;
        }
        return XMLVIEWSERVICE_WSDL_LOCATION;
    }

}
